# Generated by Django 3.1.5 on 2021-06-06 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200, verbose_name='nadpis Blogu')),
                ('product_description', models.TextField(verbose_name='Text')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='uploaded_posts', verbose_name='obrazok')),
                ('blog_description2', models.TextField(blank=True, verbose_name='Text2')),
                ('blog_figure2', models.ImageField(blank=True, null=True, upload_to='uploaded_posts', verbose_name='obrazok pod text2')),
                ('blog_figure2_des', models.TextField(max_length=300, verbose_name='popis obrazku2')),
                ('blog_figure2_2', models.ImageField(blank=True, null=True, upload_to='uploaded_posts', verbose_name='druhy obrazok pod text2')),
                ('blog_figure2_2_des', models.TextField(max_length=300, verbose_name='popis obrazku2_2')),
                ('blog_description3', models.TextField(blank=True, verbose_name='Text3')),
                ('blog_figure3', models.ImageField(blank=True, null=True, upload_to='uploaded_posts', verbose_name='obrazok pod text3')),
                ('blog_figure3_des', models.TextField(max_length=300, verbose_name='popis obrazku3')),
                ('blog_figure3_2', models.ImageField(blank=True, null=True, upload_to='uploaded_posts', verbose_name='druhy obrazok pod text3')),
                ('blog_figure3_2_des', models.TextField(max_length=300, verbose_name='popis obrazku3_2')),
                ('blog_description4', models.TextField(blank=True, verbose_name='Text4')),
                ('blog_figure4', models.ImageField(blank=True, null=True, upload_to='uploaded_posts', verbose_name='obrazok pod text4')),
                ('blog_figure4_des', models.TextField(max_length=300, verbose_name='popis obrazku4')),
                ('blog_figure4_2', models.ImageField(blank=True, null=True, upload_to='uploaded_posts', verbose_name='druhy obrazok pod text4')),
                ('blog_figure4_2_des', models.TextField(max_length=300, verbose_name='popis obrazku4_2')),
                ('blog_description5', models.TextField(blank=True, verbose_name='Text5')),
                ('blog_figure5', models.ImageField(blank=True, null=True, upload_to='uploaded_posts', verbose_name='obrazok pod text5')),
                ('blog_figure5_des', models.TextField(max_length=300, verbose_name='popis obrazku5')),
                ('blog_figure5_2', models.ImageField(blank=True, null=True, upload_to='uploaded_posts', verbose_name='druhy obrazok pod text5')),
                ('blog_figure5_2_des', models.TextField(max_length=300, verbose_name='popis obrazku5_2')),
                ('blog_description6', models.TextField(blank=True, verbose_name='Text6')),
                ('blog_figure6', models.ImageField(blank=True, null=True, upload_to='uploaded_posts', verbose_name='obrazok pod text6')),
                ('blog_figure6_des', models.TextField(max_length=300, verbose_name='popis obrazku6')),
                ('blog_figure6_2', models.ImageField(blank=True, null=True, upload_to='uploaded_posts', verbose_name='druhy obrazok pod text6')),
                ('blog_figure6_2_des', models.TextField(max_length=300, verbose_name='popis obrazku6_2')),
                ('blog_description7', models.TextField(blank=True, verbose_name='Text7')),
                ('blog_figure7', models.ImageField(blank=True, null=True, upload_to='uploaded_posts', verbose_name='obrazok pod text7')),
                ('blog_figure7_des', models.TextField(max_length=300, verbose_name='popis obrazku7')),
                ('blog_figure7_2', models.ImageField(blank=True, null=True, upload_to='uploaded_posts', verbose_name='druhy obrazok pod text7')),
                ('blog_figure7_2_des', models.TextField(max_length=300, verbose_name='popis obrazku7_2')),
                ('blog_description8', models.TextField(blank=True, verbose_name='Text8')),
                ('blog_figure8', models.ImageField(blank=True, null=True, upload_to='uploaded_posts', verbose_name='obrazok pod text8')),
                ('blog_figure8_des', models.TextField(max_length=300, verbose_name='popis obrazku8')),
                ('blog_figure8_2', models.ImageField(blank=True, null=True, upload_to='uploaded_posts', verbose_name='druhy obrazok pod text8')),
                ('blog_figure8_2_des', models.TextField(max_length=300, verbose_name='popis obrazku8_2')),
                ('blog_description9', models.TextField(blank=True, verbose_name='Text9')),
                ('blog_figure9', models.ImageField(blank=True, null=True, upload_to='uploaded_posts', verbose_name='obrazok pod text9')),
                ('blog_figure9_des', models.TextField(max_length=300, verbose_name='popis obrazku9')),
                ('blog_figure9_2', models.ImageField(blank=True, null=True, upload_to='uploaded_posts', verbose_name='druhy obrazok pod text9')),
                ('blog_figure9_2_des', models.TextField(max_length=300, verbose_name='popis obrazku9_2')),
                ('blog_description10', models.TextField(blank=True, verbose_name='Text10')),
                ('blog_figure10', models.ImageField(blank=True, null=True, upload_to='uploaded_posts', verbose_name='obrazok pod text10')),
                ('blog_figure10_des', models.TextField(max_length=300, verbose_name='popis obrazku10')),
                ('blog_figure10_2', models.ImageField(blank=True, null=True, upload_to='uploaded_posts', verbose_name='druhy obrazok pod text10')),
                ('blog_figure10_2_des', models.TextField(max_length=300, verbose_name='popis obrazku10_2')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(verbose_name='date_added')),
                ('favorite_product', models.ManyToManyField(related_name='favorite_post', to='my_app.Product', verbose_name='blog ktorý sa mu páči')),
                ('who_liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='použivatel ktorému sa to páči')),
            ],
        ),
    ]
