# Generated by Django 3.1.5 on 2021-06-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='blog_figure10_2_des',
            field=models.TextField(blank=True, max_length=300, verbose_name='popis obrazku10_2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blog_figure10_des',
            field=models.TextField(blank=True, max_length=300, verbose_name='popis obrazku10'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blog_figure2_2_des',
            field=models.TextField(blank=True, max_length=300, verbose_name='popis obrazku2_2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blog_figure2_des',
            field=models.TextField(blank=True, max_length=300, verbose_name='popis obrazku2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blog_figure3_2_des',
            field=models.TextField(blank=True, max_length=300, verbose_name='popis obrazku3_2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blog_figure3_des',
            field=models.TextField(blank=True, max_length=300, verbose_name='popis obrazku3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blog_figure4_2_des',
            field=models.TextField(blank=True, max_length=300, verbose_name='popis obrazku4_2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blog_figure4_des',
            field=models.TextField(blank=True, max_length=300, verbose_name='popis obrazku4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blog_figure5_2_des',
            field=models.TextField(blank=True, max_length=300, verbose_name='popis obrazku5_2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blog_figure5_des',
            field=models.TextField(blank=True, max_length=300, verbose_name='popis obrazku5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blog_figure6_2_des',
            field=models.TextField(blank=True, max_length=300, verbose_name='popis obrazku6_2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blog_figure6_des',
            field=models.TextField(blank=True, max_length=300, verbose_name='popis obrazku6'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blog_figure7_2_des',
            field=models.TextField(blank=True, max_length=300, verbose_name='popis obrazku7_2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blog_figure7_des',
            field=models.TextField(blank=True, max_length=300, verbose_name='popis obrazku7'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blog_figure8_2_des',
            field=models.TextField(blank=True, max_length=300, verbose_name='popis obrazku8_2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blog_figure8_des',
            field=models.TextField(blank=True, max_length=300, verbose_name='popis obrazku8'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blog_figure9_2_des',
            field=models.TextField(blank=True, max_length=300, verbose_name='popis obrazku9_2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blog_figure9_des',
            field=models.TextField(blank=True, max_length=300, verbose_name='popis obrazku9'),
        ),
    ]
