# Generated by Django 3.0.8 on 2020-08-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(blank=True, upload_to='my_app/static/uploaded_posts'),
        ),
    ]
