# Generated by Django 3.0.8 on 2022-06-22 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteProduct',
            new_name='FavoriteBlog',
        ),
        migrations.AlterField(
            model_name='blog',
            name='product_image',
            field=models.ImageField(null=True, upload_to='uploaded_posts', verbose_name='obrazok'),
        ),
    ]
