# Generated by Django 3.0.8 on 2020-09-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_likedproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikedProduct',
        ),
    ]
