# Generated by Django 3.0.8 on 2020-09-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_favoriteproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteproduct',
            name='favorite_product',
        ),
        migrations.AddField(
            model_name='favoriteproduct',
            name='favorite_product',
            field=models.ManyToManyField(related_name='favorite_post', to='my_app.Product'),
        ),
    ]
