# Generated by Django 3.0.8 on 2020-09-12 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20200911_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteproduct',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_added'),
            preserve_default=False,
        ),
    ]
