# Generated by Django 3.0.8 on 2020-09-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_likedproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikedProduct',
        ),
    ]
